### ISSUE TITLE
could this be used for analysis SC2 genomes?

### ISSUE THREAD

**Issue by liamxg** [RamiKrispin/ai-dev-2024-ml-workshop#15]
Dear @RamiKrispin,

Could I Know if this could be used for analysis SC2 genomes, thanks.

**Comment by RamiKrispin** [comment]
Unfortunately, I am not familiar with SC2 genome analysis. You should consider using this when you want to automate processes such as data refresh, live modeling, deploy dashboard or report to GitHub pages, etc.
